reporting-disabled = false
hostname = "localhost"

[meta]
  dir = "/data/meta"
  retention-autocreate = true
  logging-enabled = true
  pprof-enabled = false
  lease-duration = "1m0s"

[data]
  dir = "/data/db"
  engine = "tsm1"
  wal-dir = "/data/wal"
  wal-logging-enabled = true
  data-logging-enabled = true
  query-log-enabled = true
  cache-max-memory-size = 524288000
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "1h"
  compact-min-file-count = 3
  compact-full-write-cold-duration = "24h"
  max-points-per-block = 1000

[cluster]
  shard-writer-timeout = "5s"
  write-timeout = "10s"
  max-concurrent-queries = 0
  query-timeout = "0s"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0

[retention]
  enabled = true
  check-interval = "30m"

[shard-precreation]
  enabled = true
  check-interval = "10m"
  advance-period = "30m"

[monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "10s"

[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  ### Use a separate private key location.
  # https-private-key = ""
  max-row-limit = 10000

[[graphite]]
  enabled = false
  database = "graphite"
  bind-address = ":2003"
  protocol = "tcp"
  consistency-level = "one"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "1s"
  udp-read-buffer = 0

  separator = "."

[[collectd]]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  typesdb = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
  read-buffer = 0

[[opentsdb]]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = ""
  log-point-errors = true
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"

[[udp]]
  enabled = false
  bind-address = ""
  database = "udp"
  retention-policy = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
  read-buffer = 0
  udp-payload-size = 65536

[continuous_queries]
  log-enabled = true
  enabled = true
  run-interval = "1s"