version: '2'
services:
  influxdb:
    image: graanjonlo/influxdb:1.0.1
    ports:
     - "8083:8083"
     - "8086:8086"
    expose:
     - "8083"
     - "8086"
    volumes:
     - "/home/andy/docker/data/influxdb:/data"
