version: '2'
services:
  influxdb:
    image: graanjonlo/influxdb:0.12.0
    ports:
     - "8083:8083"
     - "8086:8086"
     - "8088:8088"
    expose:
     - "8083"
     - "8086"
     - "8088"
    volumes:
     - "/home/andy/docker/data/influxdb:/data"
